### DISCUSSION TITLE
Styling .vomnibarFrame advice

### DISCUSSION THREAD

**Discussion by joshbtay** [philc/vimium#4429] [General]
I would like to add custom styling for the <code>.vomnibarFrame</code> class. However, any style I add does not seem to get applied. Adding it in devtools works:
<img width="568" alt="image" src="https://github.com/philc/vimium/assets/74023548/a7e836bb-0eb1-465a-8457-b241449e8b15">

but adding it in Vimium Options does not:
``` css
.vomnibarFrame {
    backdrop-filter: blur(8px);
    background: #00000001;
    height: 100%;
    width: 100%;
    top: 50;
    left: 0;
}
```

Is there a way to get around this?
