### ISSUE TITLE
Custom CSS for HUD

### ISSUE THREAD

**Issue by jpbochi** [philc/vimium#2401]
Currently, it's possible to have a custom CSS for link hints, but not for the HUD. That's where the text appears on the lower right corner when in find mode. To be more specific, it's everything under the `.vimiumHUDFrame`.

**Comment by philc** [comment]
Today this is possible; here's an example:

```css
#hud-container {
  border: 10px solid green;
}
```
