### ISSUE TITLE
Add cVim-like scroll easing/animation

### ISSUE THREAD

**Issue by fishstik** [philc/vimium#3419]
One thing I miss coming from Chrome+cVim is the more fluid scrolling. See the gifs below, both using scroll half-page down keys:

[cvim](https://user-images.githubusercontent.com/4278123/67730050-fd01b100-f9c9-11e9-8272-9a4ae0e89e01.gif)
[vimium](https://user-images.githubusercontent.com/4278123/67730051-fd01b100-f9c9-11e9-9859-a0d75965c6a4.gif)

Relevant code in cVim for easing can be found [here](https://github.com/1995eaton/chromium-vim/blob/fe60f5fa18e5f6ec379494c346127a221307aff7/content_scripts/scroll.js) by searching for 'ease'. Would be awesome if this could be added as an option in Vimium.

A little unrelated but I also like the subtle animations for link hints in cVim:
[cvim_f](https://user-images.githubusercontent.com/4278123/67731429-83b88d00-f9ce-11e9-83ea-0c4b03b6d8aa.gif)
[vimium_f](https://user-images.githubusercontent.com/4278123/67731430-84512380-f9ce-11e9-8b1f-847b3201e9f9.gif)

**Comment by fishstik** [comment]
I added link hint animations by adding the following to the Vimium CSS:
```css
div > .vimiumHintMarker {
  animation: bounce .2s ease-out;
  ...
}
@keyframes bounce {
  0% { transform: scale(0.5); }
  50% { transform: scale(1.1); }
  100% { transform: scale(1); }
}
```

Still figuring out how to introduce more easing/duration for scrolling
