### ISSUE TITLE
Link hint text not centered

### ISSUE THREAD

**Issue by mcp292** [philc/vimium#4177]
![default](https://user-images.githubusercontent.com/49123398/202929920-d6d377cb-a889-4c85-af57-7e10b8a17517.png)

In the screenshot above, you can see that the bottom padding is larger than the top padding. This is using the default CSS in the settings page:
```css
div > .vimiumHintMarker {
/* linkhint boxes */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFF785),
  color-stop(100%,#FFC542));
border: 1px solid #E3BE23;
}

div > .vimiumHintMarker span {
/* linkhint text */
color: black;
font-weight: bold;
font-size: 12px;
}

div > .vimiumHintMarker > .matchingCharacter {
}
```

In what I understand to be [the underlying CSS defaults](https://github.com/philc/vimium/blob/master/content_scripts/vimium.css#L82), the bottom margin is `0px`, and the top margin is `1px`, which would produce the opposite visual effect, so I'm not sure what other setting is affecting this.

Overriding the padding to `4px` on all sides increases the padding, but on top of the extra "bottom padding" already present:

![4px](https://user-images.githubusercontent.com/49123398/202930393-c19bd513-6c3a-48be-9a4b-fecab4a7141a.png)

```css
div > .vimiumHintMarker {
/* linkhint boxes */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFF785),
  color-stop(100%,#FFC542));
border: 1px solid #E3BE23;
padding: 4px; /* added line */
}

div > .vimiumHintMarker span {
/* linkhint text */
color: black;
font-weight: bold;
font-size: 12px;
}

div > .vimiumHintMarker > .matchingCharacter {
}
```

Setting the top and bottom paddings manually, with an offset of `4px` seems to center things:

![4px_top_bottom](https://user-images.githubusercontent.com/49123398/202930836-44a4cd6b-43ed-4b01-a190-06e548edcebf.png)

```css
div > .vimiumHintMarker {
/* linkhint boxes */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFF785),
  color-stop(100%,#FFC542));
border: 1px solid #E3BE23;
padding-top: 4px;    /* added line */
padding-bottom: 0px; /* added line */

}

div > .vimiumHintMarker span {
/* linkhint text */
color: black;
font-weight: bold;
font-size: 12px;
}

div > .vimiumHintMarker > .matchingCharacter {
}
```

----

```txt
Vimium 1.67.3
Firefox 107.0
Arch Linux
```
