### ISSUE TITLE
[Give dark mode for firefox]vimium menus like for example if we press shift+o the menu that opens in which we type in text to search,  in firefox they doesnt respect dark mode and is in complete light mode please fix it 

### ISSUE THREAD

**Issue by HakaishinShwet** [philc/vimium#4416]
vimium menus like for example if we press shift+o the menu that opens in which we type text,   in firefox doesnt respect dark mode at all and is in complete light mode please fix it and make it by default dark or give any options in vimium to fix it.light mode things hurt eyes :-))

**Comment by PixsaOJ** [comment]
Go to `settings`>`Custom css for Vimium UI`

Paste this at the end.

Tu go further, yo can add `@media` checks to detect dark mode.
If you use Dark reader, they should be adding custom classes too.
```CSS
#vimiumHelpDialogContainer,
#vomnibar,
#vomnibar ul,
#vomnibar li,
#vomnibar .vomnibarSearchArea,
#vomnibar #vomnibarInput,
#vomnibar li em, #vomnibar li .vomnibarTitle
 {
  background-color: #272729 !important;
  color:white;
  border: 0 !important;
}
div#vimiumHelpDialog a,
#vomnibar li .vomnibarUrl {
  font-weight: bolder;
  color: #71b8f6;
}
```
