### ISSUE TITLE
CSS for link hints not working properly

### ISSUE THREAD

**Issue by DeadDork** [philc/vimium#605]
Hi there,

For a couple of months now, I've had the following in my **CSS for link hints** under _Vimium Options_:

``` CSS
div > .vimiumHintMarker {
/* linkhint boxes */ 
background: #CCCCFF;
border: 1px solid #6666CC;
padding: 0px 2px 1px 2px;
}

div > .vimiumHintMarker span {
/* linkhint text */ 
color: black;
font-weight: normal;
font-size: 13px;
}

div > .vimiumHintMarker > .matchingCharacter {
}
```

That made my link hints bigger & the background purple. In a recent update, that stopped being the case. I'll futz with this when I have more time, but if someone knows what's wrong, I'd appreciate a head's up.

Thanks!

DD
